### ISSUE TITLE
main domain name for client issue

### ISSUE THREAD

**Issue by rexluciano** [mahtab2003/MOFHY-Lite#40]
It's generates random characters instead of user input when creating new hosting account with subdomain name. The subdomain look like this: asdhjkkjsla.example.com and the user input is website.example.com, it should be like that. Because the random generated subdomain is not working. It's should be created when use custom domain name for the account.

**Comment by greenreader9** [comment]
That is not an issue. What you are seeing if the MOFH main domain, and it is created for identification. If you want the actual user domain up there, you will probably have to take the code from template/ViewAccount.php at the bottom of the file, then copy (To template/MyAccounts.php) and modify it so it only shows one domain.

The randomly generated domain will always show the suspended website page, because that is what it is supposed to show.

I also recommend you search old issues before created a new one: https://github.com/mahtab2003/MOFHY-Lite/issues/10

@mahtab2003, close requested for duplicate question.

**Comment by jaikt** [comment]
Hello @rexllc, the randomly generated domain you are referring to is the main domain, which is the pretty core of the free subdomain/custom domain resolution. It will by default redirect to [suspendeddomain.org](suspendeddomain.org). These settings are managed by iFastNet. You can refer to the MOFH API manual [here](https://api.myownfreehost.net/). This is what I've done with [RoyalityFree](https://royalityfree.com) (my website).
![image](https://user-images.githubusercontent.com/87015531/145664672-5f632705-14fc-4fa2-b3d4-0ef1179f1e4b.png)
Feel free to reply back on how I got into this!
